# Generated by Django 4.0.2 on 2022-02-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='age',
            field=models.IntegerField(),
        ),
    ]
